/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.mihtan.kiwi.core

import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        given:
        def lib = new Library()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
